bucket/urls.py
from django.urls import path
from . import views


app_name = 'bucket'

urlpatterns = [
    path('', views.bucket_detail, name='detail'),
    path('add/<int:product_id>/', views.bucket_add, name='bucket_add'),
    path('remove/<int:product_id>/', views.bucket_remove, name='bucket_remove'),
]

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bucket/', include('bucket.urls', namespace='bucket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)  # blank allows to be empty
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)  # auto_now_add automatically set the field to now when the object is first created
    updated = models.DateTimeField(auto_now=True)  # auto_now automatically set the field to now every time the object is saved

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product, Category
from bucket.forms import BucketAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    bucket_product_form = BucketAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'bucket_product_form': bucket_product_form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}My shop{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>

    <body>
        <div id="header">
            <a href="/" class="logo">iShop</a>
        </div>
        <div id="subheader">
            <div class="cart">
                {% with total_items=bucket|length %}
                    {% if bucket|length > 0 %}
                        Your cart:
                        <a href="{% url 'bucket:detail' %}">
                            {{ total_items }} item{{ total_items|pluralize }},
                            ${{ bucket.get_total_price }}
                        </a>
                    {% else %}
                        Your bucket is empty.
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>